T32: Fix profile queries after removal of isReply column from database
Project-Chirp/chirp-backend pull request #33
Opened 2023-07-11 19:04 UTC by AnindaS13

I fixed the profile page queries since they used isReply. No changes were made to the backend for the timestamps. I just made the fixes for the profile page queries here since the branch was already made and I was working on the T46 frontend with this branch.

2023-07-15 01:38 UTC, NasihNazeem approved these changes

2023-07-15 01:38 UTC, NasihNazeem commented on database/database.sql
Thanks for doing this

2023-07-17 02:00 UTC, NasihNazeem requested changes
Changes to `database.sql` required. Talked with Dennis about this

2023-07-18 06:12 UTC, Dennull requested changes

2023-07-18 06:12 UTC, Dennull commented on database/database.sql
Before we merge this I'm gonna remove these changes from `database.sql`. We should make any schema changes in separate sql files just to keep consistent with what we've been doing

2023-07-18 06:25 UTC, Dennull approved these changes

2023-07-18 06:26 UTC, NasihNazeem approved these changes

2023-07-18 06:28 UTC, merged